name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull dependencies
      run: docker-compose pull

    - name: Build site
      run: docker-compose run wiki build -v

    - name: Build production container
      run: docker build --tag docker.pkg.github.com/realorangeone/ssh-wiki:latest -f prod/Dockerfile .

    - name: Log into GitHub Docker Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} --password-stdin

    - name: Push the Docker container
      run: docker push docker.pkg.github.com/realorangeone/ssh-wiki:latest
