name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build site
      run: docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build --verbose
