name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull dependencies
      run: docker-compose pull

    - name: Build site
      run: docker-compose run wiki build
